version: '3.1'
services:
  database:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=homestead
      - POSTGRES_DB=backend